/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Usuario
 * Created: 9/11/2022
 */

-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 08:49:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recursoshumanos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `recursoshumanos` ;

-- -----------------------------------------------------
-- Schema recursoshumanos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recursoshumanos` DEFAULT CHARACTER SET utf8 ;
USE `recursoshumanos` ;



-- -----------------------------------------------------
-- Table `recursoshumanos`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`estado_civil` (
  `id_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id_estado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recursoshumanos`.`tipo_identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`tipo_identificacion` (
  `id_tipo_identificacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id_tipo_identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recursoshumanos`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `numero_identificacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `direccion` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  `tipo_identificacion_id_tipo_identificacion` INT NOT NULL,
  `estado_civil_id_estado_civil` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  CONSTRAINT `fk_funcionario_tipo_identificacion1`
    FOREIGN KEY (`tipo_identificacion_id_tipo_identificacion`)
    REFERENCES `recursoshumanos`.`tipo_identificacion` (`id_tipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_estado_civil1`
    FOREIGN KEY (`estado_civil_id_estado_civil`)
    REFERENCES `recursoshumanos`.`estado_civil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idfuncionario_UNIQUE` ON `recursoshumanos`.`funcionario` (`id_funcionario` ASC) VISIBLE;

CREATE UNIQUE INDEX `numero_identificacion_UNIQUE` ON `recursoshumanos`.`funcionario` (`numero_identificacion` ASC) VISIBLE;

CREATE INDEX `fk_funcionario_tipo_identificacion1_idx` ON `recursoshumanos`.`funcionario` (`tipo_identificacion_id_tipo_identificacion` ASC) VISIBLE;

CREATE INDEX `fk_funcionario_estado_civil1_idx` ON `recursoshumanos`.`funcionario` (`estado_civil_id_estado_civil` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `recursoshumanos`.`parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`parentesco` (
  `id_parentesco` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id_parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recursoshumanos`.`grupo_familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`grupo_familiar` (
  `id_grupo_familiar` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `funcionario_id_funcionario` INT NOT NULL,
  `parentesco_id_parentesco` INT NOT NULL,
  PRIMARY KEY (`id_grupo_familiar`),
  CONSTRAINT `fk_grupo_familiar_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `recursoshumanos`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_familiar_parentesco1`
    FOREIGN KEY (`parentesco_id_parentesco`)
    REFERENCES `recursoshumanos`.`parentesco` (`id_parentesco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_grupo_familiar_funcionario1_idx` ON `recursoshumanos`.`grupo_familiar` (`funcionario_id_funcionario` ASC) VISIBLE;

CREATE INDEX `fk_grupo_familiar_parentesco1_idx` ON `recursoshumanos`.`grupo_familiar` (`parentesco_id_parentesco` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `recursoshumanos`.`niveles_educativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`niveles_educativos` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recursoshumanos`.`universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`universidad` (
  `id_universidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id_universidad`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_universidad_UNIQUE` ON `recursoshumanos`.`universidad` (`id_universidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `recursoshumanos`.`formacion_academica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recursoshumanos`.`formacion_academica` (
  `id_formacion_academica` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NOW(),
  `fecha_actualizacion` DATETIME NULL DEFAULT NOW(),
  `funcionario_id_funcionario` INT NOT NULL,
  `universidad_id_universidad` INT NOT NULL,
  `niveles_educativos_id_nivel` INT NOT NULL,
  PRIMARY KEY (`id_formacion_academica`),
  CONSTRAINT `fk_formacion_academica_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `recursoshumanos`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formacion_academica_universidad1`
    FOREIGN KEY (`universidad_id_universidad`)
    REFERENCES `recursoshumanos`.`universidad` (`id_universidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formacion_academica_niveles_educativos1`
    FOREIGN KEY (`niveles_educativos_id_nivel`)
    REFERENCES `recursoshumanos`.`niveles_educativos` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idformacion_academica_UNIQUE` ON `recursoshumanos`.`formacion_academica` (`id_formacion_academica` ASC) VISIBLE;

CREATE INDEX `fk_formacion_academica_funcionario1_idx` ON `recursoshumanos`.`formacion_academica` (`funcionario_id_funcionario` ASC) VISIBLE;

CREATE INDEX `fk_formacion_academica_universidad1_idx` ON `recursoshumanos`.`formacion_academica` (`universidad_id_universidad` ASC) VISIBLE;

CREATE INDEX `fk_formacion_academica_niveles_educativos1_idx` ON `recursoshumanos`.`formacion_academica` (`niveles_educativos_id_nivel` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




/**
population
**/

-- tabla tipos_identificacion

INSERT INTO `recursoshumanos`.`tipo_identificacion`
(`nombre`,`descripcion`)
VALUES
('CC','Cedula ciudadania');

INSERT INTO `recursoshumanos`.`tipo_identificacion`
(`nombre`,`descripcion`)
VALUES
('TI','Tarjeta Identidad');

INSERT INTO `recursoshumanos`.`tipo_identificacion`
(`nombre`,`descripcion`)
VALUES
('CE','Cedula Extrangeria');

INSERT INTO `recursoshumanos`.`tipo_identificacion`
(`nombre`,`descripcion`)
VALUES
('PS','Pasaporte');

INSERT INTO `recursoshumanos`.`tipo_identificacion`
(`nombre`,`descripcion`)
VALUES
('OT','Otro');

-- ---------------------------------------
-- tabla estado civil
-- --------------------------------------------

INSERT INTO `recursoshumanos`.`estado_civil`
(`nombre`,`descripcion`)VALUES('SO','Soltero');

INSERT INTO `recursoshumanos`.`estado_civil`
(`nombre`,`descripcion`)VALUES('CA','Casado');

INSERT INTO `recursoshumanos`.`estado_civil`
(`nombre`,`descripcion`)VALUES('DI','Divorciado');

INSERT INTO `recursoshumanos`.`estado_civil`
(`nombre`,`descripcion`)VALUES('UL','Union Libre');

INSERT INTO `recursoshumanos`.`estado_civil`
(`nombre`,`descripcion`)VALUES('OT','Otro');

-- ---------------------------------------
-- tabla parentesco
-- --------------------------------------------

INSERT INTO `recursoshumanos`.`parentesco`
(`nombre`,`descripcion`)VALUES('ES','Esposa');

INSERT INTO `recursoshumanos`.`parentesco`
(`nombre`,`descripcion`)VALUES('EP','Esposo');

INSERT INTO `recursoshumanos`.`parentesco`
(`nombre`,`descripcion`)VALUES('HI','Hijo');

INSERT INTO `recursoshumanos`.`parentesco`
(`nombre`,`descripcion`)VALUES('SO','Sobrino');

INSERT INTO `recursoshumanos`.`parentesco`
(`nombre`,`descripcion`)VALUES('PA','Padres');

INSERT INTO `recursoshumanos`.`parentesco`
(`nombre`,`descripcion`)VALUES('OT','Otro');

-- ---------------------------------------
-- tabla universidad
-- --------------------------------------------

INSERT INTO `recursoshumanos`.`universidad`
(`nombre`,`descripcion`)VALUES('UDEA','Universidad de Antioquía');

INSERT INTO `recursoshumanos`.`universidad`
(`nombre`,`descripcion`)VALUES('IUD','Universidad Digital de Antioquía');

INSERT INTO `recursoshumanos`.`universidad`
(`nombre`,`descripcion`)VALUES('UNAL','Universidad Nacional de Colombia');

INSERT INTO `recursoshumanos`.`universidad`
(`nombre`,`descripcion`)VALUES('UNIANDES','Universidad de los Andes');

INSERT INTO `recursoshumanos`.`universidad`
(`nombre`,`descripcion`)VALUES('PUJ','Pontificia Universidad Javeriana');

-- ---------------------------------------
-- tabla nivel educatibo
-- -------------------------------------------

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('ES','Escuela');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('BA','Bachiller');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('TC','Tecnico');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('TG','Tecnologo');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('PR','Profecional');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('ESP','Especialista');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('MA','Magister');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('DR','Doctor');

INSERT INTO `recursoshumanos`.`niveles_educativos`
(`nombre`,`descripcion`)VALUES('OT','Otra');

-- ---------------------------------------
-- tabla funcionario
-- -------------------------------------------

INSERT INTO recursoshumanos.funcionario
(
numero_identificacion,
nombre,
apellido,
telefono,
direccion,
sexo,
fecha_nacimiento,
tipo_identificacion_id_tipo_identificacion,
estado_civil_id_estado_civil)
VALUES
(101896587,'Pepe','Ramoz','3304562587','calle falsa 123','masculino','1989-12-08',1,2);

INSERT INTO `recursoshumanos`.`funcionario`
(
`numero_identificacion`,
`nombre`,
`apellido`,
`telefono`,
`direccion`,
`sexo`,
`fecha_nacimiento`,
`tipo_identificacion_id_tipo_identificacion`,
`estado_civil_id_estado_civil`)
VALUES
(101392543,'Maria','Muñoz','3124667677','calle loma 123','femenino','1992-05-04',1,1);

-- ---------------------------------------
-- tabla grupo familiar
-- -------------------------------------------

INSERT INTO `recursoshumanos`.`grupo_familiar`
(
`nombre`,
`apellido`,
`direccion`,
`funcionario_id_funcionario`,
`parentesco_id_parentesco`)
VALUES
('David','Ramos','calle falsa 123',1,3);

INSERT INTO `recursoshumanos`.`grupo_familiar`
(
`nombre`,
`apellido`,
`direccion`,
`funcionario_id_funcionario`,
`parentesco_id_parentesco`)
VALUES
('Leonor','Muñoz','calle centro 456',2,5);

-- ---------------------------------------
-- tabla grupo formacion_academica
-- ------------------------------------------

INSERT INTO `recursoshumanos`.`formacion_academica`
(
`fecha_inicio`,`fecha_fin`,
`funcionario_id_funcionario`,
`universidad_id_universidad`,
`niveles_educativos_id_nivel`)
VALUES
('2015-02-17','2018-08-08',1,1,7);

INSERT INTO `recursoshumanos`.`formacion_academica`
(
`fecha_inicio`,`fecha_fin`,
`funcionario_id_funcionario`,
`universidad_id_universidad`,
`niveles_educativos_id_nivel`)
VALUES
('2019-07-02','2021-10-12',2,4,6);

